# Generated by Django 5.0.6 on 2024-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='genere',
            field=models.CharField(default='genere', max_length=100),
        ),
        migrations.AlterField(
            model_name='moviesdata',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='moviesdata',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
