# Generated by Django 5.0.6 on 2024-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviesdata_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='image',
            field=models.ImageField(default='movie_images/defaultimage.png', upload_to='movie_images'),
        ),
    ]
